   - name: adduser libfontconfig1
     shell: apt-get install -y adduser libfontconfig1

   - name: Download grafana
     shell: wget https://dl.grafana.com/oss/release/grafana_10.0.3_amd64.deb

   - name: dpkg grafana
     shell: dpkg -i grafana_10.0.3_amd64.deb

   - name: Systemctl Grafana Start
     systemd:
        name: grafana-server
        state: started
        enabled: yes
